import {
  Boat,
  Bridge,
  Cat,
  Chair,
  Chaturanga,
  Child,
  Cobra,
  CorpseArmsUp,
  Cow,
  CrescentMoon,
  DownwardFacingDog,
  EasyPose,
  Fish,
  HappyBaby,
  LordoftheFishes,
  LungePose,
  Mountain,
  Plank,
  SeatedForwardBend,
  SeatedTwist,
  StandingForwardFold,
  SupineSpinalTwist,
  UpwardFacingDog,
  WarriorOne,
} from "./ImagePath";

export const Poses = [
  {
    engName: "Boat",
    chiName: "船式",
    imagePath: Boat,
    duration: 10,
  },
  {
    engName: "Bridge",
    chiName: "橋式",
    imagePath: Bridge,
    duration: 10,
  },
  {
    engName: "Cat",
    chiName: "貓式",
    imagePath: Cat,
    duration: 10,
  },
  {
    engName: "Chair",
    chiName: "椅子式",
    imagePath: Chair,
    duration: 10,
  },
  {
    engName: "Chaturanga",
    chiName: "鱷魚式",
    imagePath: Chaturanga,
    duration: 10,
  },
  {
    engName: "Child",
    chiName: "嬰兒式",
    imagePath: Child,
    duration: 10,
  },
  {
    engName: "Cobra",
    chiName: "眼鏡蛇式",
    imagePath: Cobra,
    duration: 10,
  },
  {
    engName: "Corpse Arms Up",
    chiName: "仰臥式",
    imagePath: CorpseArmsUp,
    duration: 10,
  },
  {
    engName: "Cow",
    chiName: "牛式",
    imagePath: Cow,
    duration: 10,
  },
  {
    engName: "Crescent Moon",
    chiName: "新月式",
    imagePath: CrescentMoon,
    duration: 10,
  },
  {
    engName: "Downward Facing Dog",
    chiName: "下犬式",
    imagePath: DownwardFacingDog,
    duration: 10,
  },
  {
    engName: "Easy Pose",
    chiName: "簡易坐式",
    imagePath: EasyPose,
    duration: 10,
  },
  {
    engName: "Fish",
    chiName: "魚式",
    imagePath: Fish,
    duration: 10,
  },
  {
    engName: "Happy Baby",
    chiName: "快樂嬰兒式",
    imagePath: HappyBaby,
    duration: 10,
  },
  {
    engName: "Lord of the Fishes",
    chiName: "半魚王式",
    imagePath: LordoftheFishes,
    duration: 10,
  },
  {
    engName: "Lunge",
    chiName: "低弓步式",
    imagePath: LungePose,
    duration: 10,
  },
  {
    engName: "Mountain",
    chiName: "山式",
    imagePath: Mountain,
    duration: 10,
  },
  {
    engName: "Plank",
    chiName: "平板式",
    imagePath: Plank,
    duration: 10,
  },
  {
    engName: "Seated Forward Bend",
    chiName: "坐姿前彎式",
    imagePath: SeatedForwardBend,
    duration: 10,
  },
  {
    engName: "Seated Spinal Twist",
    chiName: "坐姿扭轉式",
    imagePath: SeatedTwist,
    duration: 10,
  },
  {
    engName: "Standing Forward Fold",
    chiName: "站立前屈式",
    imagePath: StandingForwardFold,
    duration: 10,
  },
  {
    engName: "Supine Spinal Twist",
    chiName: "脊柱扭轉式",
    imagePath: SupineSpinalTwist,
    duration: 10,
  },
  {
    engName: "Upward Facing Dog",
    chiName: "上犬式",
    imagePath: UpwardFacingDog,
    duration: 10,
  },
  {
    engName: "Warrior One",
    chiName: "戰士一式",
    imagePath: WarriorOne,
    duration: 10,
  },
];
